### ISSUE TITLE
还能用吗？

### ISSUE THREAD

**Issue by milobluebell** [wangqifan/ZhiHu#2]
现在还能用吗？ 貌似知乎已经不允许代理访问了？

**Comment by wangqifan** [comment]
不大清楚 最近都没有更新了

**Comment by milobluebell** [comment]
改一下爬个试试看呢？ 我这里用scrapy爬知乎，用代理ip做proxy也不能访问了。不知道你是不是还有其他方法

**Comment by milobluebell** [comment]
试了一下还是可以挂载proxy访问的，只是我用的ip代理池可用率比较低.
